### ISSUE TITLE
Why does `modulemd_module_get_dependencies` return an array?

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#13]
I'm working on porting MBS to libmodulemd and noticed that when running `mmd.get_dependencies()` on a v2 modulemd (became v2 via upgrade), I seem to always get a list with one element, no matter how many requires or buildrequires the modulemd specifies. To actually get those requires and buildrequires, I have to run `mmd.get_dependencies()[0].get_requires()` and  `mmd.get_dependencies()[0].get_buildrequires()`. These functions return a dictionary with all the dependencies in the modulemd.

So with that said, what circumstance causes `mmd.get_dependencies()` to return a list that is larger than one element? I would have expected that `mmd.get_dependencies()` would return a `ModulemdDependencies` directly instead of this one element list.

**Comment by sgallagher** [comment]
The [v2 format](https://github.com/fedora-modularity/libmodulemd/blob/master/spec.v2.yaml#L78) specifically requires that dependencies are a list in order to support stream expansion. However, in the specific case of an upgrade from a v1 file, you will always have a list of only one value because the v1 format could only handle a single one (hence the need for the backwards-incompatible change to v2).

See https://github.com/fedora-modularity/libmodulemd/blob/master/spec.v2.yaml#L78 for details on how this list will need to be parsed.
