### ISSUE TITLE
A critical log entry is shown when creating a Profile object from Python

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#284]
When creating a Profile object from Python, a critical log entry is shown. It seems to work regardless, but I'd like your opinion if this is normal. My preference would be for this log entry to not be shown if it's deemed safe to ignore.

Here is the reproducer:
```python
p = Modulemd.Profile()
```

Here is the output:
```
(process:2150): libmodulemd-CRITICAL **: 21:00:08.056: modulemd_profile_set_name: assertion 'g_strcmp0 (name, P_DEFAULT_STRING)' failed
```

**Comment by mprahl** [comment]
I see that there is no `set_name` method on a `Profile` object, so it seems the proper way to do this is `Modulemd.Profile.new(profile_name)`. In version 1, the following worked `profile = Modulemd.Profile(); profile.set_name(profile_name)`. I'll close this, but feel free to reopen it if the old way should be supported.

**Comment by sgallagher** [comment]
No, this is mostly intentional, though I *thought* it was supposed to throw an exception indicating that required options were not passed to the constructor. The fact that it's returning an object with no name is unexpected.

The Profile needs to have an immutable understanding of what it's name is for a variety of reasons (mostly so that when it's added to a ModuleStream, it's always keyed properly). The old behavior allowed the profile to be out of sync with the hash key to look it up.

Note that you can do this either of two ways: `Modulemd.Profile(name=profile_name)` or `Modulemd.Profile.new(profile_name)`.

**Comment by sgallagher** [comment]
OK, I remember why this happens now. The GObject format doesn't allow constructors to fail, so I still have to return the object. The closest I can get to an exception is that `libmodulemd-CRITICAL` message (which would would `assert()` if running in developer mode by passing the `G_DEBUG='fatal-warnings,fatal-criticals'` environment variable.)

This isn't really fixable, unfortunately. The best move would be to always pass `G_DEBUG='fatal-warnings,fatal-criticals'` during development/automated tests so you'll catch any of these issues. I'll update the documentation to recommend this.
