### ISSUE TITLE
merging modulemd-defaults

### ISSUE THREAD

**Issue by remicollet** [fedora-modularity/libmodulemd#381]
Perhaps related to #379 so probably already fixed, so mostly a question

I notice than when multiple repositories provide different streams (use case: AppStream + CentOS Stream,  or using "remi-modular")  if defined in a single repo (AppStream, the one which provides it and which is the reference) the default stream is lost.

For now, the workaround is to have it redefined in other repository.

**Comment by sgallagher** [comment]
@remicollet Could you provide a little more detail about what you are seeing? I want to create a test case for it so I make sure I’ve covered that situation with the recent fixes. I planned to make a release including them today, but I’d like to confirm that first.

**Comment by remicollet** [comment]
ON RHEL or CentOS 8 with **remi-modular** repo enabled

AS reported / explained by a user: https://forum.remirepo.net/viewtopic.php?id=3908

* In **AppStream**, php default stream set to 7.2
* In **remi-modular**, various alternative streams (remi-7.2, remi-7., remi-7.4),  no default set

dnf module list php show any default stream

(BTW, this is fixed now, as I defined the default stream to 7.2)

**Comment by sgallagher** [comment]
@remicollet When you say "I defined the default stream to 7.2", do you mean that you previously had a defaults entry that did not have a default stream defined (such as to provide profile defaults but not a default stream) or that you had no defaults entry in the metadata at all?

**Comment by remicollet** [comment]
Before:
```
----
document: modulemd-defaults
version: 1
data:
  module: php
  profiles:
    remi-7.2: [common]
    remi-7.3: [common]
    remi-7.4: [common]
...
```

**Comment by sgallagher** [comment]
OK, that was my suspicion. So this will indeed be resolved by #379 

What was happening with the previous logic is that, because your `version` was set to `1` and the official one in AppStream was unset (`==0`), your defaults were overriding the official ones.

With the revised merging logic, the `version` field will only come into play when resolving conflicts between the two repositories. This exact case is already included in my upstream tests, so we should be clear for upstream release.

@remicollet Would you please file a Bugzilla against RHEL 8 showing that there's a real-world issue that this is fixing? That'll make it much easier for me to get a bugfix release out the door.

**Comment by remicollet** [comment]
Done as https://bugzilla.redhat.com/show_bug.cgi?id=1761805

**Comment by sgallagher** [comment]
Thank you. I'll close this ticket as it's resolved in upstream.
