### ISSUE TITLE
v3 packager platform virtual module in requires

### ISSUE THREAD

**Issue by mcurlej** [fedora-modularity/libmodulemd#547]
Hi All,

so when i load the new v3 packager format and then run `convert_to_index` it will put `platform` virtual module in `buidrequires` and `requires`. Can we only put into `buildrequires`? The reason is that `platform` is not a real RPM that can be installed during runtime.

**Comment by sgallagher** [comment]
It has to behave this way because otherwise it would not be backwards-compatible. The point of that function is to produce a StreamV2 document that could be used with an unmodified MBS to continue building the same way it did in RHEL 8.

If you have a genuine reason to drop the runtime one, do it explicitly after the conversion.
