### ISSUE TITLE
modulemd: include checksum information into artifacts.rpm

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-modularity/libmodulemd#55]
Lookup by NEVRA is extremely slow... See filelists.xml for example how checksum is used.

I was pretty sure I have filled this RFE before, but can't find it.

**Comment by dmach** [comment]
I don't recommend using checksums. Query performance improvements will be part of new libdnf release (part of DNF 3).
If you implement the checksums, you'll have to deal with sigkeys first.
RPMs get built unsigned. Then they're signed with a Beta key and then Release key.
I don't think you want to rebuild modulemd every time an RPM gets signed.

**Comment by ignatenkobrain** [comment]
@dmach note that filelists already have to include this information so metadata has to be regenerated anyway.

Also libdnf/dnf is irrelevant here, because I'm not interested in using it.

**Comment by dmach** [comment]
Igor,
you don't seem to understand the problem.
Filelists contain checksum information, but it's an implementation detail in repomd repodata - how to connect data across 3 files where checksum represents a primary key.

I'm talking about situation when you replace an unsigned RPM in a repo with a signed copy.
Repodata refresh is expected, because repodata is not build and tracked as a proper artifact, it's an index of RPMs.

On the other hand, modulemd represents an artifact - a module. And you don't want it to depend on exact RPM checksums - or do you? In that case, we'd have to invalidate old modulemd and build a new one with new RPM checksums any time a RPM in repo gets signed.

**Comment by ignatenkobrain** [comment]
> And you don't want it to depend on exact RPM checksums - or do you

You do. Imagine that you changed license and rebuilt package with same NEVRA. This means you need to regenerate `licenses/content` yaml tag.

**Comment by sgallagher** [comment]
You can’t rebuild an RPM with the same NEVRA; the build system won’t allow it.

**Comment by ignatenkobrain** [comment]
@sgallagher depends on the buildsystem.

**Comment by sgallagher** [comment]
We're going to reopen this issue as a result of conversations at today's hackfest in Boston. We will add a new section under artifacts linking the NEVRAs to one or more hashes. The format will be discussed a bit later.

**Comment by ignatenkobrain** [comment]
```yaml
artifacts:
  rpm-map:
    - pkgid: $checksum
       type: sha256 (or any other checksum type)
       name: $rpm-name
       evr: $rpm-evr (without leading 0: )
       arch: $rpm-arch
```

This is my current proposal. We technically do not need name/evr/arch in there, but it won't hurt to have it there so it is easier to read and do some queries if needed.

**Comment by sgallagher** [comment]
I discussed this at length with @ignatenkobrain and @Conan-Kudo in #fedora-modularity on Freenode today. I think I'd like to counter-propose:
```yaml
artifacts:
  rpm:
    - bar-0:1.23-1.module_deadbeef.x86_64
  rpm-map:
    $checksum:
     hash_algorithm: sha256 (or any other checksum type)
     name: bar
     epoch: 0
     version: 1.23
     release: 1.module_deadbeef
     arch: x86_64
     nevra: bar-0:1.23-1.module_deadbeef.x86_64
```

So the effect would be that data.artifacts.rpm-map would be a YAML map keyed on a checksum. Its value would be a set of mandatory arguments comprising the hash algorithm of the checksum as well as the exploded and unexploded versions of the RPM NEVRA.

It is theoretically possible that using the bare checksum here could increase the risk of hash collisions, but in reality nearly all repodata uses the same algorithm, sha256 and the risk is vanishingly-small.

Feedback highly desired.

**Comment by ignatenkobrain** [comment]
>      nevra: bar-0:1.23-1.module_deadbeef.x86_64

I would prefer if this won't be there. It is totally useless since it is duplicating all information and also has this `0:` prefix which you have to strip out anyway if you want to do anything meaningful.

>      hash_algorithm: sha256 (or any other checksum type)

I would rather call it a `type`.. Because essentially it is a checksum type.

> It is theoretically possible that using the bare checksum here could increase the risk of hash collisions, but in reality nearly all repodata uses the same algorithm, sha256 and the risk is vanishingly-small.

Since the sha-256 and sha3-256 are same size but mean different things, there is a chance that there will be collisions... But hopefully sane people won't use different algorithms like this case.

**Comment by sgallagher** [comment]
> > ```
> >  nevra: bar-0:1.23-1.module_deadbeef.x86_64
> > ```
> 
> I would prefer if this won't be there. It is totally useless since it is duplicating all information and also has this `0:` prefix which you have to strip out anyway if you want to do anything meaningful.
> 

It is duplicating the information, but it's easier for a human or a program to match directly to the content in the `data.artifacts.rpms` section if they need to. I can be convinced otherwise, but I would find that very convenient for searching a long YAML at least.

> > ```
> >  hash_algorithm: sha256 (or any other checksum type)
> > ```
> 
> I would rather call it a `type`.. Because essentially it is a checksum type.
> 

Can we compromise on `checksum_type`? I want it to be clear.

> > It is theoretically possible that using the bare checksum here could increase the risk of hash collisions, but in reality nearly all repodata uses the same algorithm, sha256 and the risk is vanishingly-small.
> 
> Since the sha-256 and sha3-256 are same size but mean different things, there is a chance that there will be collisions... But hopefully sane people won't use different algorithms like this case.

sha-256 can collide with itself too... but it's extremely unlikely.

**Comment by Conan-Kudo** [comment]
I'm okay with compromising with `checksum_type`. However, I'd rather keep the `nevra` property, as it makes identifying and matching very cheap.

**Comment by ignatenkobrain** [comment]
> However, I'd rather keep the nevra property, as it makes identifying and matching very cheap.

I agree, but please **do not put `0:` epoch in there**. Every tooling will have to strip it out.

**Comment by ignatenkobrain** [comment]
> I'm okay with compromising with checksum_type.

metoo.

**Comment by Conan-Kudo** [comment]
> I agree, but please do not put 0: epoch in there. Every tooling will have to strip it out.

No, because most tools that are doing pure matching (like some of mine) will need it there, since the metadata format universally puts the `0` even with null epoch.

**Comment by sgallagher** [comment]
@ignatenkobrain You've already asserted that you don't need this field, so arguing over its format seems like a waste of time. Anyone who doesn't need the 0 in there can always (easily) construct the format they want from the other attributes. It's much easier to construct it than to parse it. This is just a convenience function for anyone who wants to do an exact-match comparison.

**Comment by sgallagher** [comment]
Adding @contyk @hanzz and @mprahl

**Comment by contyk** [comment]
I think @dmach has a point in those old comments.
I would like to have a solution to that problem before we decide on the actual format. modulemd is generated by MBS at build time and not all modules go through the compose process. Signing happens after the module build. How do we address that?

**Comment by sgallagher** [comment]
> I think @dmach has a point in those old comments.
> I would like to have a solution to that problem before we decide on the actual format. modulemd is generated by MBS at build time and not all modules go through the compose process. Signing happens after the module build. How do we address that?

Sorry, I replied to this on a conference call and forgot to reply on the issue. We don't actually need to decide the process before the format. As long as we agree that the metadata in theI think @dmach has a point in those old comments.
I would like to have a solution to that problem before we decide on the actual format. modulemd is generated by MBS at build time and not all modules go through the compose process. Signing happens after the module build. How do we address that? repository will end up in this format, we can figure out how to make that happen later. Agreeing on the format ahead of time will allow me to implement it while we work out the process details. So I'd appreciate a review of the current version of the proposal:

```
artifacts:
  rpm:
    - bar-0:1.23-1.module_deadbeef.x86_64
  rpm-map:
    $checksum:
     checksum_type: sha256 (or any other checksum type)
     name: bar
     epoch: 0
     version: 1.23
     release: 1.module_deadbeef
     arch: x86_64
     nevra: bar-0:1.23-1.module_deadbeef.x86_64
```

The main opportunity for concern is the risk of the $checksum key colliding with another checksum for a component elsewhere in the repodata, particularly if the checksum_type differs. While there is a non-zero chance of this occurring, I don't think the likelihood is high enough for it to be worth consideration (especially since if we ever actually hit such a case, a bump of the release number and rebuild of the component will resolve the conflict).

Any other concerns I am missing here?

**Comment by hanzz** [comment]
Storing that in CG build generated by MBS is really not possible. Before saying why, let me point of few facts about module builds related to this topic:

1) Once MBS moves module build to "done" state, it needs to generate CG build with modulemd metadata so we can actually create "some" compose with module so CI can test it and gate it to "ready" state.
2) Once the CG build is created, it cannot be changed. This is design-decision done by Koji to prevent changing already generated builds. There are some cases breaking this rul (like "maven" CG builds), but I would say Koji team will be really hard to persuade to accept patch doing this for modules.
3) There is no strict connection between "build" and "sign". You can build a module which is never signed, you can build a module which is signed month after you build it. You can even build a module and sign it with two keys if you use it in two products or Fedora releases with different sigkey.
4) The "cheksums" are specific to RPMs which are "shipped" with modulemd metadata, not to RPMs which are built by MBS. MBS has no idea if you are going to ship unsigned packages, signed packages by key A or signed packages by key B.

Let's say we would address this somehow in MBS. There are following options:

1) MBS waits until the package is signed for first and generate the CG build. This breaks gating from "done" to "ready", because we need CG build for this step with metadata describing unsigned packages. We also cannot wait forever and new sigkey can appear anytime, especially with modules which are supposed to be compatible with future releases. So cannot be done.
2) We persuade Koji devs so MBS (or some other service) can change the modulemd metadata of existing CG builds. This services would need to store the new set of `modulemd.$arch.txt` files everytime all the packages in a module are signed. That's because module can be signed multiple times with different sigkeys, but you want to have just single checksum in the modulemd file. This makes it much complex for other services consuming modules like ET or Bodhi. This **can** be done if we can persuade Koji devs, but it is still lot of work which should not be done on build side imho.
3) I'm not going to include even crazier ideas here like generating multiple CG builds... :)

The right place to do this is imho really in Pungi or other composing tool, because that tool directly influences what sigkey should the packages have and therefore can compute the checksum. In comparison to other methods, it is only addition of small code to compute the checksum and store it in the modulemd before dumping it to repodata.

**Comment by contyk** [comment]
So we talked about this a little today. I don't have a strong opinion on the format, although I'd prefer having per-algorithm sections under `rpm-map`, e.g.

```
rpm-map:
  sha256:
    (...)
```

This is a little more forgiving in case there's a checksum collision when using multiple algorithms, although collisions in general are still possible. In both cases the chances of that happening are incredibly small. I'm not sure what's possible in `primary.xml`, though. Would that work fine if there were two artifacts using different algorithms but had the same checksums? If so, we might need the checksum algorithm subsections.

We also talked about when we could do this and decided that MBS is indeed not the right place and this should happen in compose-ish stages. However, if the repo includes two identical NEVRAs with different content, we'd have the same problem as libsolv when linking them in the modulemd. We think we don't have to support this case.

We also talked about libmodulemd API and how our users are going to access the artifacts. Is the checksum enough or should it be checksum+algorithm? If the latter, should libmodulemd understand different variants of the same algorithm name, such as sha256, SHA-256 and so on?

**Comment by sgallagher** [comment]
Also, to record this from the conversation: in the unlikely event of two checksums colliding for different data, we will treat this as an error. The workaround should be as simple as a bump-and-rebuild of the offending RPM.

**Comment by sgallagher** [comment]
So, I spoke with @ignatenkobrain this morning via IRC and he also recommends Petr's counter-proposal, so I'm going to go with that. For the record:

```
artifacts:
  rpm:
    - bar-0:1.23-1.module_deadbeef.x86_64
  rpm-map:
    sha256:
      $checksum:
       name: bar
       epoch: 0
       version: 1.23
       release: 1.module_deadbeef
       arch: x86_64
       nevra: bar-0:1.23-1.module_deadbeef.x86_64
```
Also, libmodulemd will expressly *not* validate the format of the digest type. It will assume that the tools used to populate this section have written the correct format to match repomd. This is to ensure that we don't break future-compatibility by limiting the algorithms supported.

**Comment by sgallagher** [comment]
I just discovered a potential problem here. There was a few places I missed in the [changes to make libmodulemd ignore unknown keys](https://github.com/fedora-modularity/libmodulemd/commit/282d9ec48bae1b5e1a660eeba18f9739d3d97700)

One such place, unfortunately, is the keys underneath the `artifacts`. So right now, the libmodulemd shipped in RHEL 8 Beta will choke if the `rpm-map` key appears in the metadata. If we want to make sure that this is safely additive, we will need to move it out from under `artifacts`.

So, we could (for example) move it to `data.artifact-map.rpms`, which leaves room for other artifacts down the road.
```
artifacts:
  rpms:
    - bar-0:1.23-1.module_deadbeef.x86_64
artifact-map:
  rpms:
    sha256:
      $checksum:
       name: bar
       epoch: 0
       version: 1.23
       release: 1.module_deadbeef
       arch: x86_64
       nevra: bar-0:1.23-1.module_deadbeef.x86_64
```
Alternately, we can stick with the version from https://github.com/fedora-modularity/libmodulemd/issues/55#issuecomment-475225081 and assert that anyone who is using content from RHEL 8 with checksums will have to be using libmodulemd 2.2 or higher.

@contyk @ignatenkobrain @Conan-Kudo

**Comment by sgallagher** [comment]
Hang on, I think I may have been mistaken about this. My tests all run in "strict" mode so I notice unexpected keys, but it looks like this case is actually properly ignored when run in non-strict mode. Sorry for the false alarm.
