### ISSUE TITLE
Provide less ambiguous specs

### ISSUE THREAD

**Issue by rohanpm** [fedora-modularity/libmodulemd#578]
In this repo, there is a yaml_specs directory at https://github.com/fedora-modularity/libmodulemd/tree/main/yaml_specs .

These are referred to as "specs" and sometimes linked from docs or discussions to share info about the format.  However, these aren't real specifications, they are just some examples with human-oriented doc strings.  They give developers an idea of each document's structure, but no documents could be validated against these specs because they are defined ambiguously.

As an example where this comes up, here's a bug report https://bugzilla.redhat.com/show_bug.cgi?id=1984402, where the following error was observed:

```
Module yaml error: Failed to parse buildorder in component: 18446744073709551615: The integer value is larger than 9223372036854775807 [line 118 col 9]
```

At time of writing, with respect to this field, https://github.com/fedora-modularity/libmodulemd/blob/main/yaml_specs/modulemd_stream_v2.yaml says: "Integer, negative values are allowed" - so this data doesn't violate the spec, yet it's rejected by tooling.  Is it the document or the tool which is wrong here?  A good spec would help answer that.

It would be nice to have unambiguous specs which can be applied programmatically and more strictly define the behavior of the various fields.  One way of doing this would be to define specs in [json-schema](https://json-schema.org/specification.html) format (which is not JSON-specific despite the name).

**Comment by ppisar** [comment]
The implementation uses 64-bit 2-complement signed integer for storing buildorder. The quoted value 18446744073709551615 does not fit into it and this cannot be handled. I believe this is a deficiency in the specification because a similar limitation exists for "modified" field in [https://github.com/fedora-modularity/libmodulemd/blob/main/yaml_specs/modulemd_defaults_v1.yaml] format and it is documented there.

I will amend the specification to document the acceptable range.

For validating, you can use modulemd-validator program delivered in this repository.

I will look at the JSON Schema, but I worry it can handle only simple syntax constrains but not complex semantic like that "nevra" field value under "rpm-map" must be built from values of the name, epoch, version, release, arch siblings. I do not find appealing rewriting the human-readable specification into an inferior machine-redable specification. Especially if there is a tool for the machine-executed validation.

**Comment by ppisar** [comment]
Rohan, is https://github.com/fedora-modularity/libmodulemd/blob/b23b688443a5b9ef04be2bd91b7c0c907a82a493/yaml_specs/modulemd_stream_v2.yaml#L605-L621 comprehensible for you?

**Comment by rohanpm** [comment]
Yes, thank you.
